
create database QUANLYBANHANG_LTTQ

use QUANLYBANHANG_LTTQ

create table NHANVIEN
(
	NVID varchar(6),
	HOTEN nVARCHAR(40),
	SDT VARCHAR(15),
	NGVL SMALLDATETIME,
	NGSINH SMALLDATETIME,
	THUONG MONEY,
	CV NVARCHAR(20),
	USERNAME VARCHAR(40),
	PASSWD VARCHAR(40),
	LUONG MONEY,
	HESO FLOAT,
	CONSTRAINT PK_NV PRIMARY KEY (NVID)
)


CREATE TABLE KHACHHANG
(
	KHID VARCHAR(6),
	HOTEN nVARCHAR(40),
	DIACHI nVARCHAR(100),
	SDT VARCHAR (15), 
	NGDK SMALLDATETIME,
	DOANHSO MONEY,
	LOAIKH varchar(5),
	CONSTRAINT PK_KH PRIMARY KEY (KHID)
)

CREATE TABLE SANPHAM
(
	SPID VARCHAR(10),
	TENSP nVARCHAR(100),
	LOAIID NVARCHAR(20),
	HANGSX NVARCHAR(20),
	NUOCSX nVARCHAR(20), 
	GIABAN MONEY,
	GIANHAP MONEY,
	DVT NVARCHAR(10),
	SOLUONG INT,
	SLTT INT,
	MOTA nVARCHAR(1000),
	CONSTRAINT PK_SP PRIMARY KEY (SPID)
)

CREATE TABLE LOAISP
(
	LOAIID NVARCHAR(20),
	TENLOAI nVARCHAR (40),
	MOTA NVARCHAR(200),
	CONSTRAINT PK_LSP PRIMARY KEY (LOAIID)
)



CREATE TABLE DTCC
(
	DTID VARCHAR(6),
	TENDT nVARCHAR (40),
	SDT VARCHAR(15),
	NGDT SMALLDATETIME,
	DIACHI nVARCHAR(200),
	CONSTRAINT PK_DT PRIMARY KEY (DTID)
)


CREATE TABLE HDBH
(
	SOHD_BH VARCHAR(10),
	NGHD SMALLDATETIME,
	KHID VARCHAR(6),
	NVID VARCHAR(6),
	TRIGIA MONEY,
	LOAIHD nVARCHAR(20),
	TRANGTHAI nVARCHAR(20),
	CONSTRAINT PK_HDBH PRIMARY KEY (SOHD_BH)
)

create table CTHDBH
(
	SOHD_BH VARCHAR(10), 
	SPID VARCHAR(10),
	SL TINYINT
	CONSTRAINT PK_CTHD PRIMARY KEY (SOHD_BH, SPID)
)

CREATE TABLE HDNH
(
	SOHD_NH VARCHAR(10),
	NGNHAP  SMALLDATETIME,
	DTID VARCHAR(6),
	NVID VARCHAR(6),
	TRIGIA MONEY,
	CONSTRAINT PK_HDNH PRIMARY KEY (SOHD_NH)
)

CREATE TABLE CTHDNH
(
	SOHD_NH VARCHAR(10),
	SPID VARCHAR(10),
	SL TINYINT,
	CONSTRAINT PK_CTHDNH PRIMARY KEY (SOHD_NH, SPID)
)


CREATE TABLE CALAMVIEC
(
	CAID VARCHAR(6),
	THU nVARCHAR(15),
	GIO_BD TIME,
	GIO_NGHI TIME,
	CONSTRAINT PK_CLV PRIMARY KEY (CAID)
)


CREATE TABLE CT_LAMVIEC
(
	NVID VARCHAR(6), 
	CAID VARCHAR(6),
	NGAYLAM SMALLDATETIME,
	TRANGTHAI NVARCHAR(30),
	CHEDO NVARCHAR(20),
	TIEUDE NVARCHAR(100),
	CONSTRAINT PK_CTLV PRIMARY KEY (CAID, NVID,NGAYLAM)
)

CREATE TABLE CT_LAMVIEC_HANGTUAN
(
	NVID VARCHAR(6),
	CAID VARCHAR(6),
	TIEUDE NVARCHAR(100),
	CONSTRAINT PK_CTLV_HT PRIMARY KEY (CAID, NVID)
)

CREATE TABLE DOANHTHUNGAY
(
	TODAY DATETIME,
	SLHOADON INT,
	SLDONNHAP INT,
	DOANHTHU MONEY,
	TONGCHI MONEY
	CONSTRAINT PK_DTN PRIMARY KEY (TODAY)
)
create table KHUYENMAI
(
	TENKM nvarchar(100),
	DTKM nvarchar(20),
	LOAIKM nvarchar(20),
	KMTHEO nvarchar(20),
	TENDKKM nvarchar(40),
	NGAYBD smalldatetime,
	NGAYKT smalldatetime,
	QUAKEM nvarchar(70),
	CHUTHICH nvarchar(200),
	KIEUSALE nvarchar(40),
	SALE int,
	SOLUONGHANG smallint,
	GIAGIAM int,
	TUDONGXOA smallint,
	CODIEUKIEN smallint
)

 -- CAC KHOA NGOAI --

ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP FOREIGN KEY (LOAIID) REFERENCES LOAISP(LOAIID)

ALTER TABLE HDBH ADD CONSTRAINT FK_HDBH FOREIGN KEY (NVID) REFERENCES NHANVIEN(NVID)
ALTER TABLE HDNH ADD CONSTRAINT FK_HDNH FOREIGN KEY (NVID) REFERENCES NHANVIEN(NVID)
ALTER TABLE CTHDNH ADD CONSTRAINT FK_CTHDNH FOREIGN KEY (SPID) REFERENCES SANPHAM(SPID)
ALTER TABLE CTHDNH ADD CONSTRAINT FK_CTHDNH2 FOREIGN KEY (SOHD_NH) REFERENCES HDNH(SOHD_NH)
ALTER TABLE CTHDBH ADD CONSTRAINT FK_CTHDBH FOREIGN KEY (SPID) REFERENCES SANPHAM(SPID)
ALTER TABLE CTHDBH ADD CONSTRAINT FK_CTHDBH2 FOREIGN KEY (SOHD_BH) REFERENCES HDBH(SOHD_BH)


ALTER TABLE CT_LAMVIEC ADD CONSTRAINT FK_CT_LV FOREIGN KEY (NVID) REFERENCES NHANVIEN(NVID)
ALTER TABLE CT_LAMVIEC ADD CONSTRAINT FK_CT_LV2 FOREIGN KEY (CAID) REFERENCES CALAMVIEC(CAID)


--CAC DIEU KIEN --

ALTER TABLE NHANVIEN ADD CONSTRAINT DK_LV CHECK( NGVL > NGSINH)
alter table SANPHAM ADD CONSTRAINT DK_SP CHECK( GIABAN > GIANHAP)

